version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'instabug_chat_development'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Abc@123456'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql


  redis:
    image: redis:6.2.14
    volumes:
      - redis-data:/data
    networks:
      - default
  
  elasticsearch:
    image: elasticsearch:8.14.3
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"


  app:
    build: 
      context: .
      dockerfile: docker/rails/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - elasticsearch

volumes:
  my-db:
  redis-data:
  esdata01:
